# Troubleshooting:
#     In case there is an error when installing sklearn: run pip install
#        Cython==0.29.23 manually and then run the above command again.
#     In case you have access to a GPU, see instructions [here]
#        (https://github.com/google/jax#pip-installation-gpu-cuda) for installing
#        the GPU version of jaxlib. This will make the experiment run
#        significantly faster.
name: fsvi
channels:
- defaults
- conda-forge
- anaconda
- pytorch
dependencies:
- python=3.7
- pip=21.0.1
- ipython
- pillow
- psutil
- jupyter
- seaborn=0.10.1
- tabulate=0.8.7
- tqdm=4.48.2
- plotly=4.9.0
- urllib3=1.26.4
- pytorch=1.8.1
- torchvision=0.9.1
- cpuonly=1.0
- cython=0.29.23  # cython must be installed before scikit-learn
- cudatoolkit=11.1
- pip:
  - --find-links https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
  - jax==0.2.11
  - jaxlib==0.1.64+cuda112
  - neural-tangents==0.3.6
  - uncertainty-metrics==0.0.81
  - latex==0.7.0
  - scikit-learn==0.21.3
  - scipy==1.6.2
  - seqtools==1.1.0
  - pandas==1.3.5
  - pyreadr
  - gpustat==0.6.0
  - tensorflow-datasets==4.2.0
  - tfp-nightly==0.12.0.dev20201117
  - uncertainty_metrics
  - joypy
  - pytest
  - retry==0.9.2
  - dm-haiku==0.0.4
  - optax==0.0.2
  - chex==0.0.7
  - dm-sonnet==2.0.0
  - dm-tree==0.1.6
  - keras==2.6.0
  - gpflow==2.2.1
  - tensorflow-probability==0.13.0
  - tensorflow-addons==0.13.0
